<?php

namespace App\Filament\Owner\Resources\RoomCategories\Pages;

use App\Filament\Owner\Resources\RoomCategories\RoomCategoryResource;
use App\Models\Room;
use Filament\Resources\Pages\CreateRecord;
use Filament\Notifications\Notification;

class CreateRoomCategory extends CreateRecord
{
    protected static string $resource = RoomCategoryResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        // Clean up data based on room creation method
        if (isset($data['auto_generate_rooms'])) {
            unset($data['auto_generate_rooms']);
        }

        if (isset($data['number_of_rooms'])) {
            unset($data['number_of_rooms']);
        }

        if (isset($data['room_number_prefix'])) {
            unset($data['room_number_prefix']);
        }

        if (isset($data['room_number_start'])) {
            unset($data['room_number_start']);
        }

        if (isset($data['default_floor'])) {
            unset($data['default_floor']);
        }

        return $data;
    }

    protected function afterCreate(): void
    {
        $data = $this->form->getRawState();
        $category = $this->record;

        // Handle auto-generated rooms
        if (isset($data['auto_generate_rooms']) && $data['auto_generate_rooms']) {
            $this->createAutoGeneratedRooms(
                $category,
                $data['number_of_rooms'] ?? 1,
                $data['room_number_prefix'] ?? 'R',
                $data['room_number_start'] ?? 101,
                $data['default_floor'] ?? '1'
            );
        }
        // Handle manually added rooms
        elseif (isset($data['rooms']) && is_array($data['rooms']) && count($data['rooms']) > 0) {
            foreach ($data['rooms'] as $roomData) {
                Room::create([
                    'room_category_id' => $category->id,
                    'room_number' => $roomData['room_number'],
                    'floor' => $roomData['floor'],
                    'status' => $roomData['status'] ?? 'available',
                ]);
            }
        }

        // Update total rooms count
        $category->refresh();
        $category->updateTotalRooms();

        Notification::make()
            ->success()
            ->title('Room category created successfully')
            ->body("Created {$category->total_rooms} rooms for {$category->name}")
            ->send();
    }

    private function createAutoGeneratedRooms(
        $category,
        int $count,
        string $prefix,
        int $startNumber,
        string $floor
    ): void {
        for ($i = 0; $i < $count; $i++) {
            $roomNumber = $prefix . ($startNumber + $i);

            Room::create([
                'room_category_id' => $category->id,
                'room_number' => $roomNumber,
                'floor' => $floor,
                'status' => 'available',
            ]);
        }
    }

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('view', ['record' => $this->record]);
    }
}
